In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
dataset = pd.read_csv("Churn_Modelling.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:, 2])
from sklearn. compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform (X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7632
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4551 - accuracy: 0.7968
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4392 - accuracy: 0.8004
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4281 - accuracy: 0.8101
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4190 - accuracy: 0.8160
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4099 - accuracy: 0.8256
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4009 - accuracy: 0.8313
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3931 - accuracy: 0.8347
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3864 - accuracy: 0.8376
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3812 - accura